/*
 * generated by Xtext 2.21.0
 */
package org.xtext.ide

import org.xtext.ide.server.codeAction.FlyCodeActionService
import org.eclipse.xtext.ide.server.codeActions.ICodeActionService2

/**
 * Use this class to register ide components.
 */
class FLYIdeModule extends AbstractFLYIdeModule {
	
	def Class<? extends ICodeActionService2> bindICodeActionService2() {
		FlyCodeActionService
	}
}
